backend:
  name: git-gateway
  repo: pastpatryk/drabina-web
  branch: master
media_folder: "src/_images/uploads"
public_folder: "images/uploads"

collections:
  - label: "Strony"
    name: "pages"
    delete: false
    files:
      - label: "Główna"
        name: "main"
        file: "src/_data/main.yml"
        fields:
          - label: "Nagłówek"
            name: "about_title"
            widget: "string"
          - label: "Opis"
            name: "about_body"
            widget: "markdown"
          - label: "Sztuka"
            name: "sztuka_title"
            widget: "string"
          - label: "Sztuka opis"
            name: "sztuka_body"
            widget: "markdown"
